Update main2.yml

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -14,10 +14,10 @@ jobs:
 
       - name: Download and Setup Zig
         run: |
-          wget https://github.com/x20888450/zig/releases/download/Releases/a.zip
-          unzip a.zip
-          mv ./bin $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
-          mv ./include $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
+          wget -O a.zip https://github.com/x20888450/zig/releases/download/Releases/a.zip || { echo 'Download failed'; exit 1; }
+          unzip a.zip || { echo 'Unzip failed'; exit 1; }
+          mv ./bin $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin || { echo 'Move bin failed'; exit 1; }
+          mv ./include $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include || { echo 'Move include failed'; exit 1; }
 
       - name: Build Project
         run: |
